<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
	<LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
	<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<Company />
	<Description>HashAlgorithms</Description>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<RepositoryUrl>https://github.com/pairbit/IT.Hashing</RepositoryUrl>
	<PublishRepositoryUrl>true</PublishRepositoryUrl>
	<Authors>Ivan Tikhonov</Authors>
	<Copyright>Ivan Tikhonov © 2026</Copyright>
	<Version>2.0.2</Version>
	<PackageTags>Gost Hashing Native CryptoPro VipNet</PackageTags>
	<PackageReadmeFile>Readme.md</PackageReadmeFile>
	<PackageIcon>Icon.png</PackageIcon>
	<PackageReleaseNotes></PackageReleaseNotes>
	<SignAssembly>true</SignAssembly>
	<AssemblyOriginatorKeyFile>..\IT.snk</AssemblyOriginatorKeyFile>
	<IncludeSymbols>true</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	<EmbedUntrackedSources>true</EmbedUntrackedSources>
	<DebugType>full</DebugType>
	<NoWarn>$(NoWarn);IDE1006;IDE0049</NoWarn>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Readme.md" Pack="true" PackagePath="\" />
    <None Include="..\Icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework) == 'netstandard2.0'">
    <PackageReference Include="System.Memory" Version="4.6.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.301" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IT.Hashing.Gost\IT.Hashing.Gost.csproj" />
  </ItemGroup>

</Project>
